version: "3"
services:
  postgresql:
    image: postgres
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - /home/jahn/postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.hostname == minion-4]
      
  coinmarketcap-producer:
    image: jahnestacado/coinmarketcap-producer
    environment:
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: ${HOST_IP:?HOST_IP must be set}:19092,${HOST_IP}:29092,${HOST_IP}:39092
      KAFKA_PRODUCER_SCHEMA_REGISTRY_URL: http://${HOST_IP}:8085
      CMC_COIN_IDS: "1,2,1831,1027,52"

  twitter-producer:
    image: jahnestacado/twitter-producer
    environment:
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: ${HOST_IP}:19092,${HOST_IP}:29092,${HOST_IP}:39092
      KAFKA_PRODUCER_SCHEMA_REGISTRY_URL: http://${HOST_IP}:8085
      TWITTER_TRACKS: "bitcoin,BTC,etherium,ETH,ripple,XRP,litecoin,LTC,bitcoin-cash,BHC,cryptocurrency,crypto"

  postgresql-sink:
    image: jahnestacado/postgresql-sink
    depends_on:
        - postgresql
    environment:
      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: ${HOST_IP}:19092,${HOST_IP}:29092,${HOST_IP}:39092
      KAFKA_SCHEMA_REGISTRY_URL: http://${HOST_IP}:8085
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
    deploy:
      mode: replicated
      replicas: 2

